name: Promote Python Package

on:
  repository_dispatch:
    types: [cloudsmith-package-synchronized]

permissions:
  id-token: write 
  contents: read

env:
  CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
  CLOUDSMITH_STAGING_REPO: 'staging'
  CLOUDSMITH_PRODUCTION_REPO: 'production'
  CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}
  PACKAGE_NAME: 'example_package'

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Cloudsmith CLI
        run: |
          python -m pip install --upgrade pip
          pip install cloudsmith-cli

      - name: Exchange OIDC Token for Cloudsmith API Key
        run: |
          echo "Retrieving OIDC token from GitHub..."
          OIDC_VALUE=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')

          echo "Exchanging OIDC token with Cloudsmith..."
          CLOUDSMITH_TOKEN=$(curl -s -X POST -H "Content-Type: application/json" \
            -d "{\"oidc_token\":${OIDC_VALUE}, \"service_slug\":\"${{ env.CLOUDSMITH_SERVICE_SLUG }}\"}" \
            "https://api.cloudsmith.io/openid/${{ env.CLOUDSMITH_NAMESPACE }}/" | jq -r '.token')

          if [ "$CLOUDSMITH_TOKEN" = "null" ] || [ -z "$CLOUDSMITH_TOKEN" ]; then
            echo "ERROR: Failed to retrieve Cloudsmith API key from OIDC token!"
            exit 1
          fi

          echo "Successfully retrieved Cloudsmith API key!"
          echo "CLOUDSMITH_API_KEY=$CLOUDSMITH_TOKEN" >> $GITHUB_ENV

      - name: Verify Cloudsmith Authentication
        run: |
          echo "Verifying Cloudsmith auth..."
          cloudsmith whoami --api-key $CLOUDSMITH_API_KEY

      - name: Tag Package as Ready for Production
        run: |
          echo "Tagging package with 'ready-for-production'..."
          PACKAGE_QUERY="filename:${PACKAGE_NAME}-${{ github.event.client_payload.package_version }}.tar.gz"
          PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} \
            --api-key $CLOUDSMITH_API_KEY \
            -q "$PACKAGE_QUERY" -F json)
          
          IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm')
          
          if [ "$IDENTIFIER" = "null" ] || [ -z "$IDENTIFIER" ]; then
            echo "ERROR: Package not found in staging!"
            exit 1
          fi
          
          cloudsmith tag add ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
            ready-for-production --api-key $CLOUDSMITH_API_KEY

      - name: Promote Package to Production
        run: |
          echo "Promoting packages tagged 'ready-for-production' to production..."
          PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} \
            --api-key $CLOUDSMITH_API_KEY \
            -q "tag:ready-for-production" -F json)
          
          IDENTIFIERS=$(echo "$PACKAGE_DATA" | jq -r '.data[].identifier_perm')

          if [ -z "$IDENTIFIERS" ]; then
            echo "ERROR: No packages found with 'ready-for-production' tag!"
            exit 1
          fi

          for ID in $IDENTIFIERS; do
            cloudsmith mv --yes \
              ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$ID \
              ${{ env.CLOUDSMITH_PRODUCTION_REPO }} \
              --api-key $CLOUDSMITH_API_KEY
          done

          echo "Promotion completed!"
